### ISSUE TITLE
README documentation for 3.2 does not mention lack of support for OMOP CDM

### ISSUE THREAD

**Issue by evs2008** [hestiri/DQe-c#3]
Hi all,

Looks like you removed support for OMOP in 3.2. Do you mind adding this to the readme so that other users know right away to go to 3.1 if they want to run it on OMOP?

**Comment by hestiri** [comment]
Currently, OMOP specifications are missing to add functionality on OMOP. We'll be adding it soon.

**Comment by evs2008** [comment]
Should this issue be resolved as part of https://github.com/data2health/DQe-c-v2/?

**Comment by hestiri** [comment]
Yes!
